CREATE TABLE `p1_candidates` (
  `candidate_id` varchar(4) NOT NULL,
  `name_surname` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `gender` varchar(1) DEFAULT NULL,
  `birth_year` int DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `phone` varchar(45) DEFAULT NULL,
  `mail` varchar(45) DEFAULT NULL,
  `linkedin` varchar(45) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `school` varchar(45) DEFAULT NULL,
  `major` varchar(45) DEFAULT NULL,
  `business_skills` varchar(45) DEFAULT NULL,
  `licences` varchar(45) DEFAULT NULL,
  `languages` varchar(45) DEFAULT NULL,
  `current_position` varchar(45) DEFAULT NULL,
  `work_experience` varchar(45) DEFAULT NULL,
  `optimal_position` varchar(45) DEFAULT NULL,
  `talent_score` int DEFAULT NULL,
  `project_ID` varchar(4) DEFAULT NULL,
  `blacklisted` varchar(5) DEFAULT NULL,
  `kn1_description` varchar(45) DEFAULT NULL,
  `kn1_score` varchar(45) DEFAULT NULL,
  `kn2_description` varchar(45) DEFAULT NULL,
  `kn2_score` varchar(45) DEFAULT NULL,
  `competencies` varchar(45) DEFAULT NULL,
  `c_description` text DEFAULT NULL,
  `pv_description` text DEFAULT NULL,
  PRIMARY KEY (`candidate_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
